version: "3.9"

services:
  mongodb_container:
    image: bitnami/mongodb:5.0
    environment:
      MONGODB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/bitnami/mongodb
volumes:
  mongodb_data:
